Feature/room id generation
GameFuse-PA/back pull request #13
Opened 2023-05-25 08:27 UTC by noeoxycode

2023-05-25 09:29 UTC, Pbonnamy requested changes

2023-05-25 09:29 UTC, Pbonnamy commented on package.json
> +    "uuid": "^9.0.0"
a enlever

2023-05-25 09:29 UTC, Pbonnamy commented on src/room/room.controller.ts
> +@Controller('room')
nom de la ressource au pluriel

2023-05-25 09:29 UTC, Pbonnamy commented on src/room/room.controller.ts
> +    @Get('roomCreation')
@Post()

2023-05-25 09:29 UTC, Pbonnamy commented on src/room/room.controller.ts
> +    getFriends(@Request() req) {
fonction à rename

2023-05-25 09:29 UTC, Pbonnamy commented on src/room/room.controller.ts
> +        return id;
a remplacer par un appel de service

2023-05-25 09:29 UTC, Pbonnamy commented on src/room/room.service.ts
> +
ajouter un schema room avec juste un id et ajouter une methode create dans ce service

2023-05-25 09:29 UTC, Pbonnamy commented on src/room/roomModule.ts
> +    imports: [UsersModule, JwtModule, FileModule, FriendsModule],
Trop d'import la dedans faut que tu mette que ce que tu utilise vraiment

2023-05-27 05:07 UTC, Pbonnamy commented on src/room/roomModule.ts
> +    imports: [UsersModule, JwtModule, FileModule, FriendsModule],
pas sure que t'ai besoin de file module

2023-06-18 21:21 UTC, Pbonnamy requested changes

2023-06-18 21:21 UTC, Pbonnamy commented on src/room/room.service.ts
> +    }
a revoir

2023-06-23 12:17 UTC, ShadowZ11 approved these changes

2023-06-23 12:20 UTC, merged