display games endpoint
GameFuse-PA/back pull request #17
Opened 2023-06-18 14:38 UTC by Pbonnamy

Get /games with search query param

2023-06-18 21:48 UTC, noeoxycode requested changes

2023-06-18 21:48 UTC, noeoxycode commented on src/games/games.service.ts
> +        program: Express.Multer.File,
ne faudrait-il pas controler les données avant de les utiliser ?

2023-06-18 21:48 UTC, noeoxycode commented on src/games/games.service.ts
> +                const bannerFile = await this.fileService.uploadFile(
tu fais de la suppression et l'upload de fichiers
ça casse srp
on s'en fiche ?
si on ne s'en fiche pas, il peut être judicieux de split ça en plusieurs méthodes

2023-06-18 22:02 UTC, Pbonnamy commented on src/games/games.service.ts
> +        program: Express.Multer.File,
Tu veux valider quoi ?

2023-06-18 22:02 UTC, Pbonnamy commented on src/games/games.service.ts
> +                const bannerFile = await this.fileService.uploadFile(
tu voudrais split comment ?

2023-06-19 21:28 UTC, noeoxycode requested changes

2023-06-19 21:28 UTC, noeoxycode commented on src/games/games.service.ts
> +        program: Express.Multer.File,
notamment le gameId, tu fais un find ligne 97, mais ça va crash si la valeur est null

2023-06-19 21:28 UTC, noeoxycode commented on src/games/games.service.ts
> +                const bannerFile = await this.fileService.uploadFile(
updateGameProperties
updateBanner
updateProgram

2023-06-19 21:28 UTC, noeoxycode commented on src/games/games.service.ts
> +                const bannerFile = await this.fileService.uploadFile(
mais c'est plus une question qu'une modif à faire absolument
si pour toi ce n'est pas nécessaire laisse on laisse comme ça

2023-06-19 21:31 UTC, Pbonnamy commented on src/games/games.service.ts
> +        program: Express.Multer.File,
en soit je le check dans le contoller si le jeu existe et ligne 97 ca va pas crash juste yaura un resultat null mais je check ce cas la avec mon if  ligne 99

2023-06-19 21:31 UTC, Pbonnamy commented on src/games/games.service.ts
> +                const bannerFile = await this.fileService.uploadFile(
le raisonnement se tient après je pense pas qu'on va etre amené à réutiliser ce code ailleurs donc vu la taille du projet je pense que le laisser ca passe

2023-06-19 21:35 UTC, noeoxycode approved these changes

2023-06-21 20:54 UTC, merged