Feature/list my match
GameFuse-PA/back pull request #19
Opened 2023-06-23 15:17 UTC by ShadowZ11

Config game session + get my game session

2023-06-23 18:45 UTC, Pbonnamy requested changes

2023-06-23 18:45 UTC, Pbonnamy commented on src/game-session/game-session.controller.ts
> +@Controller('game-session')
au pluriel les noms de ressource

2023-06-23 18:45 UTC, Pbonnamy commented on src/game-session/game-session.service.ts
> +    async getMyParties(id: string) {
soit c gameSessions soit parties (je serais plus partant pour le gamesessions ou juste sessions

2023-06-25 20:31 UTC, Pbonnamy requested changes

2023-06-25 20:31 UTC, Pbonnamy commented on src/game-session/enum/game-session.enum.ts
> +export enum GameSessionEnum {
GameSessionStatus je pense

2023-06-25 20:31 UTC, Pbonnamy commented on src/game-session/game-session.controller.spec.ts
> +describe('PartiesController', () => {
a modif

2023-06-25 20:31 UTC, Pbonnamy commented on src/game-session/game-session.service.spec.ts
> +describe('PartiesService', () => {
a modif

2023-06-25 20:39 UTC, ShadowZ11 commented on src/game-session/enum/game-session.enum.ts
> +export enum GameSessionEnum {
Yep j'hésitais au début et je me suis dit comme c'est un enum pk pas, mais c'est vrai qu'en convention de nommage on dit pas GameSessionClass par exemple

2023-06-25 20:45 UTC, Pbonnamy approved these changes

2023-06-25 22:03 UTC, merged