Feature/create party
GameFuse-PA/back pull request #21
Opened 2023-06-25 23:36 UTC by ShadowZ11

Feature de création d'une partie

2023-07-02 13:25 UTC, noeoxycode requested changes

2023-07-02 13:25 UTC, noeoxycode commented on src/game-session/dto/game-session.dto.ts
> +    winner: string;
on ne devait pas mettre de winner normalement : et-ce une erreur ou un choix ?
GameSession {
  chat : Message[],
  visio : Visio,
  history : GameAction[],
  players : User[]
}

2023-07-04 21:09 UTC, Pbonnamy requested changes

2023-07-04 21:09 UTC, Pbonnamy commented on src/game-session/dto/game-session.dto.ts
> +    winner: string;
ouais on ajoutera quand on aura besoin sur que la c un create game session dto donc yaura pas de winner à la création

2023-07-04 21:09 UTC, Pbonnamy commented on src/game-session/dto/game-session.dto.ts
> +    createdBy: string;
Req.user ca

2023-07-04 22:45 UTC, Pbonnamy approved these changes

2023-07-05 20:52 UTC, Pbonnamy approved these changes

2023-07-05 20:56 UTC, noeoxycode approved these changes

2023-07-05 21:40 UTC, merged