Feature/refonte friends
GameFuse-PA/back pull request #22
Opened 2023-06-28 18:56 UTC by ShadowZ11

Refonte de la partie amis avec initialisation des fichiers de conversations et le schema d'invitations

2023-06-28 19:53 UTC, noeoxycode requested changes

2023-06-28 19:53 UTC, noeoxycode commented on src/friends/friends.service.ts
> +            friend.idFriends,
pas sûr de ça : tu fais un findOne sur un tableau d'id que tu attribues à une variable

2023-06-28 19:53 UTC, noeoxycode commented on src/friends/friends.service.ts
>      async addFriend(id: string, friend: FriendsDto) {
id n'est pas assez explicite : de qui est-ce l'id ?

2023-06-28 19:53 UTC, noeoxycode commented on src/friends/friends.service.ts
>      async deleteFriend(idUser: string, idFriend: string) {
je préfère remove plutot que delete mais à toi de statuer

2023-06-28 19:53 UTC, noeoxycode commented on src/profil/profile.service.ts
> +            friends: friends.friends,
friends.friends ? ça me parait étrange je ne suis pas sûr de comprendre

2023-06-28 19:53 UTC, noeoxycode commented on src/schemas/conversation.schema.ts
> +        required: true,
ça ne va pas poser problème ? car on crée la conversation au moment de la création de l'amitié, mais il n'ya  pas encore de message.
Si ça pose problème je vois deux solutions : retirer le required ou alors envoyer un message bateau dans la conv du style : "c'est le début d'une nouvelle amitié !"

2023-06-28 19:53 UTC, noeoxycode commented on src/schemas/invitations.schema.ts
> +    receiver: string;
tu as oublié la date

2023-06-28 19:53 UTC, noeoxycode commented on src/users/users.controller.ts
> +    @Post('invitations')
invitation au singulier ou friendRequest
entre autre : un nom plus parlant que juste invitation

2023-06-28 19:53 UTC, noeoxycode commented on src/users/users.service.ts
> +        const userExist = await this.userModel.findById(userId);
userExist n'est pas parlant comme nom

2023-06-28 19:53 UTC, noeoxycode commented on src/users/users.service.ts
> +            throw new InternalServerErrorException(
pas d'exception perso ? une erreur 500 pour ça ne me semble pas adéquat

2023-06-28 19:53 UTC, noeoxycode commented on src/users/users.service.ts
> +                'La personne vous possède déjà dans ses amis',
le user ne doit pas avoir le détail
tu peux logger pour le debug mais le user doit juste savoir qu'une erreur liée à l'amitié a eu lieu

2023-06-28 19:53 UTC, noeoxycode commented on src/users/users.service.ts
> +        await this.notificationsService.sendEmail(
ça fait beaucoup de choses dans une même méthode

2023-06-28 19:53 UTC, noeoxycode commented on src/users/users.service.ts
> +        await this.notificationsService.sendEmail(
après si on ne revient pas sur ce code plus tard et que c'est sûr qu'il marche pas obligé de changer

2023-06-28 19:53 UTC, noeoxycode commented on src/configuration/mail.config.service.ts
> +    getInvitationMail(username: string, token: string) {
invitationMail : plutot friendRequest ou équivalent plus parlant : invitation est trop général

2023-06-28 20:29 UTC, ShadowZ11 commented on src/schemas/conversation.schema.ts
> +        required: true,
Non en soit, parce que j'ai mis une valeur par défaut qui est un tableau vide d'où le "default: []" dans le prop, donc no problem dès que tu vas créer la conversation en db il va automatiquement créer un tableau vide

2023-06-28 20:30 UTC, ShadowZ11 commented on src/schemas/invitations.schema.ts
> +    receiver: string;
C'est pas grave ici parce que j'ai mis @Schema({ versionKey: false, timestamps: true }) faut juste récupérer la date de création de la ligne qui est créer automatiquement lors de la création de la ligne

2023-06-28 20:45 UTC, ShadowZ11 commented on src/users/users.service.ts
> +        await this.notificationsService.sendEmail(
Yes je sais, mais après en soit l'invitation fera jamais autre chose que ce que j'ai mis donc check error -> création du model dans la db -> envoi de l'email de notif
après pour la partie de l'envoi de l'email je peux le mettre dans une méthode privée à part mais ça reviendrai au même en soit

2023-06-28 20:58 UTC, ShadowZ11 commented on src/profil/profile.service.ts
> +            friends: friends.friends,
Yes, petit problème de nommage avec le premier friends, en gros je dois populate le friends avec qui est l'utilisateur en soit et friends c'est le champ du model qui est un tableau de tes amis

2023-06-29 09:01 UTC, noeoxycode commented on src/profil/profile.service.ts
> +            friends: friends.friends,
j'ai pas tellement mieux compris mdr désolé

2023-06-29 16:10 UTC, Pbonnamy requested changes

2023-06-29 16:10 UTC, Pbonnamy commented on src/conversations/conversations.controller.ts
> +@Controller('conversation')
au pluriel

2023-06-29 16:10 UTC, Pbonnamy commented on src/conversations/dto/message.dto.ts
> +    from: string;
ca devrait etre le user authentifier (req.userid)

2023-06-29 16:10 UTC, Pbonnamy commented on src/friends/friends.service.ts
>          }
en soit l'annotation fait deja ce travail

2023-06-29 16:10 UTC, Pbonnamy commented on src/friends/friends.service.ts
>          };
alors c un peu du détail mais les messages de retour c censé etre géré par le controller depuis un service tu renvoit plus un booléen

2023-06-29 16:10 UTC, Pbonnamy commented on src/schemas/conversation.schema.ts
> +}
Faut un message document

2023-06-29 16:10 UTC, Pbonnamy commented on src/users/users.controller.ts
> +    @Post('invitations')
en fait pour moi soit c  /users/:id/invite
soit c un inviationController
et tu fait un post sur /invitations
-> perso je ferait la 2eme sachant que tu va devoir la modif par la suite pour accepter / refuser

2023-06-29 16:10 UTC, Pbonnamy commented on src/users/users.service.ts
> +        };
comme mentionner plus haut le service return l'invitation , si tu veux renvoyer un message c dans le controller

2023-06-29 21:52 UTC, ShadowZ11 commented on src/friends/friends.service.ts
>          };
ouais après je t'avoue j'ai un peu recopié ce qui avait été fait dans le auth.service et notifications.service 😅

2023-06-29 21:52 UTC, ShadowZ11 commented on src/schemas/conversation.schema.ts
> +}
Bah après j'avoue que le document on s'était dit avec Noé que c'éatait pas forcément une bonne idée parce qu'on va pas stocké un message précis en db donc une interface seule était plus utile

2023-06-29 21:54 UTC, ShadowZ11 commented on src/users/users.controller.ts
> +    @Post('invitations')
Pour moi ça a plus de sens de faire /users/:id/invite, parce que juste un controller invitations ça a pas de sens dans le principe ou je t'invite pour quoi (partie, devenir ami etc...)

2023-06-29 22:43 UTC, Pbonnamy commented on src/schemas/conversation.schema.ts
> +}
en soit je pense que ca reste utile le from ca va etre une relation

2023-06-29 22:43 UTC, Pbonnamy commented on src/friends/friends.service.ts
>          };
ouais j'ai vu en fait tu le fait a pas mal d'endroit

2023-06-29 22:43 UTC, Pbonnamy commented on src/friends/friends.service.ts
>          };
laisse tomber alors c aps très grave

2023-07-01 11:27 UTC, Pbonnamy approved these changes

2023-07-01 11:31 UTC, noeoxycode approved these changes

2023-07-01 11:36 UTC, merged