V2 Profil
GameFuse-PA/back pull request #23
Opened 2023-06-29 22:16 UTC by Pbonnamy

modify update profil & fix/optimizations

2023-06-29 22:53 UTC, noeoxycode requested changes

2023-06-29 22:53 UTC, noeoxycode commented on src/profil/profile.service.ts
> +            if (user.avatar) {
ne faudrait-il pas plutot mettre le delete directement dans le service ? le service check si le fichier existe, si oui il le supprime et le remplace. Là; ça veut dire qu'à chaque fois qu'on voudra upload une photo ailleurs faudra delete puis upload
je pense que uploadPhoto n'a pas à connaitre le process derrière

2023-06-29 23:05 UTC, Pbonnamy commented on src/profil/profile.service.ts
> +            if (user.avatar) {
Jsp trop ça veut dire passer l'id en paramètre de la fonction sachant que des fois t'en aura pas (dans le cas d'un upload de création)

2023-06-29 23:07 UTC, Pbonnamy commented on src/profil/profile.service.ts
> +            if (user.avatar) {
Et du coup la fonction dupload a un peu 2 comportements

2023-06-30 06:27 UTC, noeoxycode approved these changes

2023-06-30 19:38 UTC, merged