Feature/search function update
GameFuse-PA/back pull request #25
Opened 2023-07-02 00:33 UTC by ShadowZ11

refonte de la recherche user niveau back

2023-07-02 00:59 UTC, noeoxycode requested changes

2023-07-02 00:59 UTC, noeoxycode commented on src/users/users.service.ts
> +        for (const user of usersSearch) {
pourquoi est-ce que tu ne récupères pas directement les amis de l'utilisateur ? par exemple en précisant de trouver tous les users dont friends contient l'id du user

2023-07-02 18:22 UTC, Pbonnamy approved these changes

2023-07-03 09:51 UTC, noeoxycode approved these changes

2023-07-03 09:53 UTC, merged