Feature/conversations
GameFuse-PA/back pull request #30
Opened 2023-07-16 13:38 UTC by noeoxycode

conversations pour room et message privé fonctionnel
chat video fonctionnel

2023-07-17 11:00 UTC, Pbonnamy requested changes

2023-07-17 11:00 UTC, Pbonnamy commented on src/schemas/messages.schema.ts
> +    date: number;
type date

2023-07-17 11:00 UTC, Pbonnamy commented on src/profil/profile.controller.ts
> +    @Get('game-session/:id')
au pluriel

2023-07-17 11:00 UTC, Pbonnamy commented on src/schemas/conversation.schema.ts
> +    isGameChat: boolean;
a quoi ca sert ca ? tu l'utilise pas niveau front

2023-07-17 11:00 UTC, Pbonnamy commented on src/liveChat/liveChat.service.ts
> +        console.log('jenvoie le msg');
console.log

2023-07-17 11:00 UTC, Pbonnamy commented on src/liveChat/liveChat.service.ts
> +        }*/
a enlever si pas utiliser

2023-07-17 11:00 UTC, Pbonnamy commented on src/liveChat/liveChat.service.ts
> +        console.log('saved message : ' + savedMessage);
console.log

2023-07-17 11:00 UTC, Pbonnamy commented on src/guards/WebSocketAuthGuard.ts
> +            // @ts-ignore
ts ignore

2023-07-17 11:00 UTC, Pbonnamy commented on src/guards/WebSocketAuthGuard.ts
>              console.log('Le token renseigné est invalide');
console.log

2023-07-17 21:12 UTC, noeoxycode commented on src/schemas/conversation.schema.ts
> +    isGameChat: boolean;
dans le cadre d'une conversation privée entre deux joueurs je cherche les conversations où isGameChat est false
car une gameSession a une conversation aussi, et un joueur A et un B peuvent avoir leur conversation privée et également une gameSession à deux : pour distinguer les deux je rajoute cette propriété.
l'autre solution possible aurait été de créer une nouvelle entité de conversation spécifique aux games sessions mais comme l'objet est identique, j'ai trouvé plus judicieux de les distinguer simplement par ce boolean

2023-07-17 21:12 UTC, noeoxycode commented on src/schemas/conversation.schema.ts
> +    isGameChat: boolean;
dans getConversations de conversation.service j'ai un filtre pour ça dans mon find

2023-07-17 21:12 UTC, noeoxycode commented on src/guards/WebSocketAuthGuard.ts
> +            // @ts-ignore
je suis obligé : c'est un problème entre socket.io et nest. Socket.io ne fourni pas d'informations de type de retour à nest

2023-07-17 21:12 UTC, noeoxycode commented on src/schemas/messages.schema.ts
> +    date: number;
à débattre

2023-07-18 19:34 UTC, Pbonnamy commented on src/guards/WebSocketAuthGuard.ts
> +            // @ts-ignore
a mon avis tu peux typer en any ca doit faire le taff

2023-07-18 21:40 UTC, Pbonnamy approved these changes

2023-07-18 21:41 UTC, merged